version: '3.1'

services:
  postgres-letrinha:
    image: postgres:14-alpine
    environment:
      POSTGRES_DATABASE: letrinha
      POSTGRES_PASSWORD: letrinha
      POSTGRES_USER: letrinha
    expose:
      - "5432"
    healthcheck:
      interval: 3s
      retries: 3
      test: PGPASSWORD=letrinha psql -h localhost -U letrinha -c '\l'
      timeout: 3s
    ports:
      - "5432:5432"
    volumes:
      - ./prisma/data/postgres-letrinha:/var/lib/postgresql/data
  mongo-letrinha:
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: letrinha
      MONGO_INITDB_ROOT_USERNAME: letrinha
      MONGO_INITDB_ROOT_PASSWORD: letrinha